
export const properties = [
  {
    id: "luxury-villa-in-bali",
    name: "Luxury Villa in Bali",
    location: "Bali, Indonesia",
    price: "$2,500,000",
    yield: "6.8%",
    imageUrl: "/properties/bali.png",
    description: "A stunning 5-bedroom villa with an infinity pool overlooking the ocean. Fully furnished and ready for rental.",
    totalShares: 10000,
    sharesAvailable: 3450,
  },
  {
    id: "penthouse-in-new-york",
    name: "Penthouse in New York",
    location: "New York, USA",
    price: "$5,000,000",
    yield: "4.5%",
    imageUrl: "/properties/newyork.png",
    description: "A luxurious penthouse in the heart of Manhattan with breathtaking city views. Features a private rooftop terrace.",
    totalShares: 25000,
    sharesAvailable: 11200,
  },
  {
    id: "beachfront-condo-in-miami",
    name: "Beachfront Condo in Miami",
    location: "Miami, USA",
    price: "$1,200,000",
    yield: "5.2%",
    imageUrl: "/properties/miami.png",
    description: "A modern 2-bedroom condo with direct beach access and resort-style amenities.",
    totalShares: 5000,
    sharesAvailable: 1200,
  },
  {
    id: "chalet-in-the-swiss-alps",
    name: "Chalet in the Swiss Alps",
    location: "Zermatt, Switzerland",
    price: "$3,000,000",
    yield: "4.0%",
    imageUrl: "/properties/swiss.png",
    description: "A cozy ski-in/ski-out chalet with stunning mountain views of the Matterhorn.",
    totalShares: 15000,
    sharesAvailable: 5500,
  },
  {
    id: "apartment-in-tokyo",
    name: "Apartment in Tokyo",
    location: "Tokyo, Japan",
    price: "$800,000",
    yield: "3.5%",
    imageUrl: "/properties/tokyo.png",
    description: "A stylish apartment in the vibrant Shibuya district, close to transport and amenities.",
    totalShares: 4000,
    sharesAvailable: 800,
  },
  {
    id: "ranch-in-texas",
    name: "Ranch in Texas",
    location: "Texas, USA",
    price: "$1,500,000",
    yield: "2.8%",
    imageUrl: "/properties/ranch-texas.png",
    description: "A sprawling ranch with over 100 acres of land, perfect for cattle or recreational use.",
    totalShares: 7500,
    sharesAvailable: 3000,
  },
];

export type Property = (typeof properties)[0];
